### PR TITLE
Check pending wayland events in the queue on source preapre

### PR DESCRIPTION
**Pull request by carlosgcampos**
It's causing delays when there are multiple targets in the same process.

### CODE REVIEW

**Comment by carlosgcampos** [comment]
This is the reason for the poor rendering performance in WebKitGTK when having two related web views (sharing the same web process).

**Comment by carlosgcampos** [comment]
hmm, sorry, I made a mistake in my tests, this patch doesn't fix the issue. I'll keep investigating.

**Comment by carlosgcampos** [comment]
Sure, I'm working on a new patch, I'll reuse this PR

**Comment by aperezdc** [comment]
It took me a bit of thinking to wrap my head about the changes, but they do look good. Thanks a lot for the patch!

**Pull request merged**
